### ISSUE TITLE
Update to 1.7.3

### ISSUE THREAD

**Issue by comxd** [plynchnlm/prototypejs-bower#1]
Hi,

Please update to 1.7.3.

**Comment by plynchnlm** [comment]
Thanks for the reminder.  I don't actually use this package anymore, but let me know if you run into a problem with the update.  @jwestbrook also has a bower package registered for Prototype, "prototype.js", which I wish I could recommend switching to, and would except that 1) it appears to be at 1.7.3-beta, instead of 1.7.3, 2) the tags on the repository are missing some versions, and 3) I seem to recall that his versions are not quite the same code as the versions from the official website (but maybe that can change now that 1.7.3 is out).  Anyway, given the frequency of updates to Prototype, it is not much trouble to keep this going if it is still useful.

**Comment by jwestbrook** [comment]
Whoops I'll make sure I update mine to the right version - thanks for the poke

**Comment by comxd** [comment]
Good, thanks for your replies! :)
